spring:
  datasource:
    url: jdbc:h2:mem:userdb
    driverClass: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8085
  servlet:
      context-path: /api/user/v1/

